spring:
  application:
    name: eureka-server
server:
  port: 10086
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: true
    eviction-interval-timer-in-ms: 2000
    enable-self-preservation: false
    service-url:
      defaultZone: http://localhost:10086/eureka/